### ISSUE TITLE
fabric 1.20.1 version 1.0.0 of the mod says it requires 1.20.2

### ISSUE THREAD

**Issue by HatTrkPatrk** [Lightningbulb2/EyeOfEnderFix#1]
![image](https://github.com/Lightningbulb2/EyeOfEnderFix/assets/5185596/a7a1a8b4-9326-479e-9a4d-5790e02d374d)

**Comment by Lightningbulb2** [comment]
Just recompiled the fabric mod with different properties so now it will run for 1.20 - 1.20.4
